format = """
$status\
$cmd_duration\
$time"""

add_newline = false

[cmd_duration]
min_time = 500
format = "[took](bold) [$duration](bold yellow) [at](bold) "


[status]
#symbol = "âœ˜"
format = '[$symbol$status $common_meaning ]($style) '
map_symbol = true
disabled = false

[time]
disabled = false
format = 'ðŸ•™ [$time ]($style) '
time_format = "%r"
